=== StephenCarlson/BYU-Mars-Rover/RoverLink.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of simple elements -->
<xs:element name="include" type="xs:anyURI"/> <!-- Not sure what this does, keep? -->
<xs:element name="version" type="xs:unsignedByte"/>
<xs:element name="description" type="xs:string"/>


<!-- definition of attributes -->
<xs:attribute name="name"> <!-- enum,entry,message,field -->
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-z0-9_]{1,30}(\[([0-9])+\])?"/>
			<!-- I gave up on trying to imitate the mavlink generator, it can do uint8_t[8],
					I will have to stick with payload[8]. Thus, allows [] on names. -->
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>
<xs:attribute name="target"> <!-- enum,entry,message,field -->
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-z0-9_]{1,30}){1}( ##name)?"/>
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>
<xs:attribute name="id" type="xs:unsignedByte"/> <!-- message -->
<xs:attribute name="value"> <!-- entry -->
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{1,10}"/> <!-- base 10 int -->
			<xs:pattern value="0[xX][0-9a-fA-F]{1,8}"/> <!-- base 16 -->
			<xs:pattern value="0[bB][0-1]{1,32}"/> <!-- base 1 -->
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>
<xs:attribute name="minValue"> <!-- entry -->
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="-?\d{1,10}"/> <!-- base 10 int -->
			<xs:pattern value="0[xX][0-9a-fA-F]{1,8}"/> <!-- base 16 -->
			<xs:pattern value="0[bB][0-1]{1,32}"/> <!-- base 1 -->
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>
<xs:attribute name="maxValue"> <!-- entry -->
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="-?\d{1,10}"/> <!-- base 10 int -->
			<xs:pattern value="0[xX][0-9a-fA-F]{1,8}"/> <!-- base 16 -->
			<xs:pattern value="0[bB][0-1]{1,32}"/> <!-- base 1 -->
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>
<xs:attribute name="initValue"> <!-- entry -->
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="-?\d{1,10}"/> <!-- base 10 int -->
			<xs:pattern value="0[xX][0-9a-fA-F]{1,8}"/> <!-- base 16 -->
			<xs:pattern value="0[bB][0-1]{1,32}"/> <!-- base 1 -->
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>
<xs:attribute name="type">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="int8_t(\[([0-9])+\])?"/>
			<xs:pattern value="uint8_t(\[([0-9])+\])?"/>
			<xs:pattern value="int16_t(\[([0-9])+\])?"/>
			<xs:pattern value="uint16_t(\[([0-9])+\])?"/>
			<xs:pattern value="int32_t(\[([0-9])+\])?"/>
			<xs:pattern value="uint32_t(\[([0-9])+\])?"/>
			<xs:pattern value="int64_t(\[([0-9])+\])?"/>
			<xs:pattern value="uint64_t(\[([0-9])+\])?"/>
			<xs:pattern value="systemState_t"/>
			<xs:pattern value="messageMask_t"/>
			<xs:pattern value="broadcast_t"/>
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>
<xs:attribute name="access">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="READ_ONLY"/>
			<xs:pattern value="WRITE_ONLY"/>
			<xs:pattern value="READ_WRITE"/>
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>

<!-- definition of complex elements -->

<xs:element name="entry">
	<xs:complexType mixed="true">
		<xs:sequence>
			<xs:element ref="description" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute ref="value" use="required"/>
		<xs:attribute ref="name" use="required"/>
	</xs:complexType>
</xs:element>

<xs:element name="field">
	<xs:complexType mixed="true"> <!-- mixed allows text to appear between <field> and </field> tags -->
		<xs:sequence>
			<xs:element ref="description" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute ref="type" use="required"/>
		<xs:attribute ref="name" use="required"/>
		<xs:attribute ref="minValue"/>
		<xs:attribute ref="maxValue"/>
		<xs:attribute ref="initValue"/>
	</xs:complexType>
</xs:element>

<xs:element name="constant">
	<xs:complexType mixed="true">
		<xs:sequence>
			<xs:element ref="description" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute ref="type" use="required"/>
		<xs:attribute ref="name" use="required"/>
		<xs:attribute ref="value" use="required"/>
	</xs:complexType>
</xs:element>

<xs:element name="typedef">
	<xs:complexType mixed="true">
		<xs:sequence>
			<xs:element ref="description" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute ref="type" use="required"/>
		<xs:attribute ref="name" use="required"/>
	</xs:complexType>
</xs:element>

<xs:element name="enum">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="description" minOccurs="0"/>
			<xs:element ref="entry" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="name" use="required"/>
		<xs:attribute ref="target" use="required"/>
	</xs:complexType>
</xs:element>

<xs:element name="message">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="description" minOccurs="0"/>
			<xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="id" use="required"/>
		<xs:attribute ref="name" use="required"/>
		<xs:attribute ref="access" use="required"/>
	</xs:complexType>
</xs:element>

<xs:element name="constants">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="constant" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="typedefs">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="typedef" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="enums">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="enum" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="messages">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="message" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="roverlink">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="include" minOccurs="0"/>
			<xs:element ref="version" minOccurs="0"/>
			<xs:element ref="constants" minOccurs="0"/>
			<xs:element ref="typedefs" minOccurs="0"/>
			<xs:element ref="enums" minOccurs="0"/>
			<xs:element ref="messages"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== StephenCarlson/BYU-Mars-Rover/RoverLink.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- 
	BYU Mars Rover UDP Message Protocol, October 2014.
	Mostly inspired by MAV Link: https://pixhawk.ethz.ch/mavlink/
	Credits: 
		Steve Carlson
		<Your name here>
		
	FAQs:
	What is this, and how do I use it?
		This is a description of the UDP protocol, in XML. It is more flexible than a spreadsheet, though not quite as readable.
		The prime purpose of recording this in XML is as follows:
			Allows for GIT to track changes, rather than the cursed binary format of most spreadsheets.
			Allows for the C header files that describe the entire protocol to be generated easily by a script.
	This is messed up, the formatting is trashed, tabs are chaos!
		Use Notepad++ with tabs=4, or whatever editor you use, each tab is 4 spaces.
		Also, attempted to keep lines within 150 character long when possible.
	This is really complicated!
		Well, sort of, is there a simpler way to do all this?
		Two extremes: [Send every single variable as a separate packet/message] and [Send the entire set of variables at once in a huge message]
		The protocol below strikes the balance between granularity and uniformity. Variables are packet into messages by what they control and how.
		The parts of the protocol that need work are the packet anatomy; Do we need a Sequence counter? READ/WRITE bit?

	xmlns="RoverLink.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
-->
<roverlink xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RoverLink.xsd">

	<version>3</version>
	<constants>
		<constant type="uint8_t" name="WRITE_BIT"	value="0x80">The Message Id is bitwise ORed with this to designate a write</constant>
		<constant type="uint8_t" name="REQUEST_BIT"	value="0x40">The Message Id is bitwise ORed with this to designate a request</constant>
	</constants>
	<typedefs>
		<typedef type="uint8_t"		name="systemState_t"></typedef>
		<typedef type="uint16_t"	name="messageMask_t"></typedef>
		<typedef type="uint8_t"		name="broadcast_t"></typedef>
	</typedefs>
	<enums>
		<enum name="BOARD_ID" target="board_id">
			<description>List of possible aliases. Each board belongs to only one kind of alias/group.</description>
				<!-- This lets our boards be UDP port and IP Address agnostic. No reason to fret about IP addresses on the rover or basestation -->
			<entry value="0" name="BASESTATION">
				<description>The Primary Basestation</description></entry>
			<entry value="1" name="MAIN_CONTROLLER">
				<description>Only a single Main Controller board, with Drive, Camera, Gimbal and Power control responsibilities.</description></entry>
			<entry value="2" name="ARM_CONTROLLER">
				<description>Only a single Arm Controller board, solely responsible for the arm and other related systems.</description></entry>
			<entry value="8" name="BASESTATION_2">
				<description>A second Ethernet device in the basestation tent, possibly the Arm Puppet.</description></entry>
		</enum>
		<enum name="SYSTEM_STATE" target="systemState">
			<description>systemState field in the heartbeat and status messages that indicates board health</description>
			<entry value="0" name="STARTUP">
				<description>Initial State, board is booting up.</description></entry>
			<entry value="1" name="NORMAL">
				<description>Normal operation.</description></entry>
			<entry value="2" name="FAILSAFE">
				<description>Code is stable, but rover has lost link. Enter benign state: Turn off scary lasers, stop wheels, etc.</description></entry>
			<entry value="3" name="ERROR">
				<description>If the board crashes, this probably won't even be reached, but if possible, this signals that code has crashed.</description></entry>
		</enum>
		<enum name="GPS_FIX_TYPE" target="fix_type">
			<description>fix_type in the GPS message</description>
			<entry value="0" name="NONE"><description>No Fix</description></entry>
			<entry value="1" name="FIX_2D"><description>2D Fix</description></entry>
			<entry value="2" name="FIX_3D"><description>Full Solution</description></entry>
			<entry value="3" name="OTHER"><description>Other or unknown</description></entry>
		</enum>
		<enum name="MESSAGE_MASK" target="messageMask_t ##name"> <!-- Fantastically dangerious to use the "##" operator, is a precompiler macro,
				but it was the only thing I could think of that describes capturing whatever variables use the messageMask_t typedef. -->
			<description>The Telemetry Config and One-Shot Message Mask. Basically, 2^(Message Id) forms the bitmask field.</description>
			<entry value="0x0001" name="HEALTH_HEARTBEAT"></entry>
			<entry value="0x0002" name="ROVER_STATUS"></entry>
			<entry value="0x0004" name="ARM_STATUS"></entry>
			<entry value="0x0008" name="RESERVED_1"></entry>
			<entry value="0x0010" name="GPS_POSITION"></entry>
			<entry value="0x0020" name="IMU_SAMPLE"></entry>
			<entry value="0x0040" name="RESERVED_2"></entry>
			<entry value="0x0080" name="DRAGONLINK_FRAME"></entry>
			<entry value="0x0100" name="DRIVE_SETPOINTS"></entry>
			<entry value="0x0200" name="VIDEO_SETPOINTS"></entry>
			<entry value="0x0400" name="ARM_SETPOINTS"></entry>
			<entry value="0x0800" name="ISHAAMA"></entry>
			<entry value="0x1000" name="LIFERAY"></entry>
			<entry value="0x2000" name="CUSTOM_DEBUG_1"></entry>
			<entry value="0x4000" name="CUSTOM_DEBUG_2"></entry>
			<entry value="0x8000" name="CUSTOM_DEBUG_3"></entry>
		</enum>
		<enum name="BROADCAST_COMMAND" target="broadcastCommand">
			<description>Broadcast Message</description>
			<entry value="0x01" 		name="SAVE_FAILSAFE_VALUES_NOW">Save setpoint values for if link lost later.</entry>
			<entry value="0xF0" 		name="PANIC_STOP">If any of the upper 4 bits != 0, panic stop.</entry>
		</enum>
	</enums>
	<messages>
		<message id="0" name="HEALTH_HEARTBEAT" access="READ_ONLY">
			<description>Each board must provide a status report of its health periodically.</description>
			<field type="uint32_t"		name="systemTimestamp"								>Milliseconds from boot</field>
			<field type="systemState_t"	name="systemState"	minValue="0" maxValue="3"		>System status code, see enum definition</field>
			<field type="uint16_t"		name="cpuLoad"		minValue="0" maxValue="1000"	>The CPU Load, 0% means idle, 100% means saturated</field>
			<field type="uint16_t"		name="busErrors"									>Count of I2C/SPI Bus errors</field>
			<field type="uint16_t"		name="ethernetErrors"								>Count of Ethernet errors</field>
			<field type="uint16_t"		name="someOtherMetric"								>Probably packet lag time, etc</field>
		</message>
		<message id="1" name="ROVER_STATUS" access="READ_ONLY">
			<description>The Main Controller Board handles the Camera and Gimbal, Drive and Power systems.</description>
			<field type="systemState_t"	name="systemState"		minValue="0"		maxValue="3"		>System status code, see enum definition</field>
			<field type="uint16_t"		name="roverVoltage"		minValue="0"		maxValue="60000"	>Voltage in mV, Ex: 12450 means 12.450 Volts</field>
			<field type="int16_t"		name="roverCurrent"		minValue="-20000"	maxValue="20000"	>Current in 10mA, Ex: 16500 means 165.00 Amps</field>
			<field type="int32_t"		name="mAhCounter"		minValue="0"		maxValue="100000"	>Battery used in mAh</field>
			<field type="uint16_t"		name="ubntLinkInteg"	minValue="0"		maxValue="1000"		>100% means perfect link, 0% is lost link, in 0.1% units</field>
			<field type="uint16_t"		name="dragonLinkRSSI"	minValue="0"		maxValue="1000"		>Same as ubntLinkInteg, for backup-link LRS receiver</field>
		</message>
		<message id="2" name="ARM_STATUS" access="READ_ONLY">
			<description>The Arm Controller Board handles the Arm, including PID controllers. May also handle soil taster "ISHAAMA".</description>
			<field type="uint8_t"	name="systemState"	minValue="0" maxValue="3"	>System status code</field>
			<field type="uint16_t"	name="dynamixelErrors"							>Number of bad reads or writes to Dynamixel servos.</field>
			<field type="int16_t"	name="pid1_error"	minValue="-2000"	maxValue="2000">Error as in the error term, a scalar value.</field>
			<field type="int16_t"	name="pid2_error"	minValue="-2000"	maxValue="2000">Same as above, for the 2nd PID controller</field>
			<field type="int16_t"	name="pid3_error"	minValue="-2000"	maxValue="2000">Same as above, for the 3rd PID controller</field>
		</message>
		<message id="3" name="RESERVED_1" access="READ_ONLY">
			<description>Reserved for future use.</description>
		</message>
		<message id="4" name="GPS_POSITION" access="READ_ONLY">
			<description>Parsed NMEA sentence data. May disband these fields in favor of echoing entire NMEA sentence.</description>
			<field type="int32_t"	name="lat"		minValue="-899999999"	maxValue="899999999"	>Latitude in 1E-7 units</field>
			<field type="int32_t"	name="lon"		minValue="-1799999999"	maxValue="1799999999"	>Longitude in 1e-7 units</field>
			<field type="int32_t"	name="alt"		minValue="-10000000"	maxValue="10000000"		>Altitude in millimeters</field>
			<field type="uint16_t"	name="hdop"		minValue="0"			maxValue="60000"		>Horizontal DOP in centimeters</field>
			<field type="uint16_t"	name="vdop"		minValue="0"			maxValue="60000"		>Vertical DOP in centimeters</field>
			<field type="uint16_t"	name="vel"		minValue="0"			maxValue="2000"			>Velocity in cm/sec</field>
			<field type="uint16_t"	name="course"	minValue="0"			maxValue="3599"			>Course in 0.1 degrees units</field>
			<field type="uint8_t"	name="fix_type"	minValue="0"			maxValue="3"			>Fix Type, see the enum definition</field>
			<field type="uint8_t"	name="sats"		minValue="0"			maxValue="30"			>Number of satellites locked on</field>
		</message>
		<message id="5" name="IMU_SAMPLE" access="READ_ONLY">
			<description>The samples from the IMU, probably a MPU-9250. North-East-Down conventions.</description>
			<field type="int16_t" name="xacc"	>X Acceleration, Front+</field>
